#+ method: POST
#+ endpoint: http://0.0.0.0:3030/recipes/query
#+ summary: Get Recipes that contain given category
#+ defaults:
#+   - cat: Beef

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?category_name ?recipe_name ?recipe
{
  ?recipe rdf:type schema:Recipe;
          schema:name ?recipe_name;
          schema:recipeCategory ?category.
  ?category rdf:type schema:Text;
            rdf:value ?category_name.
  FILTER contains(lcase(?category_name), lcase(?_cat_string))
}
ORDER BY ?category_name