#+ method: POST
#+ endpoint: http://0.0.0.0:3030/recipes/query
#+ summary: Get recipes in fat range
#+ defaults:
#+   - fl: 100.0
#+   - fu: 500.0

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?recipe ?recipe_name ?fatContent
{
  ?recipe rdf:type schema:Recipe;
          schema:name ?recipe_name;
          schema:nutrition ?nutrition.
  ?nutrition schema:fatContent ?fatContent.
  FILTER (xsd:float(?fatContent) >= ?_fl_float && xsd:float(?fatContent) <= ?_fu_float)
}
ORDER BY xsd:float(?fatContent) ?recipe_name