#+ method: GET
#+ endpoint: http://172.18.0.1:3030/recipes/query
#+ summary: Get Recipes that contain given ingredient (TODO make ingredient configurable)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?ingredient_name ?recipe_name ?recipe
{
  ?recipe rdf:type schema:Recipe;
          schema:name ?recipe_name;
          schema:recipeIngredient ?ingredient.
  ?ingredient rdf:type schema:Text;
            rdf:value ?ingredient_name.
  FILTER contains(lcase(?ingredient_name), lcase("Beef"))
}
ORDER BY ?ingredient_name