#+ method: GET
#+ endpoint: http://0.0.0.0:3030/recipes/query
#+ summary: Get recipes in protein content range (TODO: make protein content range configurable)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?recipe ?recipe_name ?proteinContent
{
  ?recipe rdf:type schema:Recipe;
          schema:name ?recipe_name;
          schema:nutrition ?nutrition.
  ?nutrition schema:proteinContent ?proteinContent.
  FILTER (xsd:float(?proteinContent) >= 10.0 && xsd:float(?proteinContent) <= 20.0)
}
ORDER BY xsd:float(?proteinContent) ?recipe_name